
title: aussiedwarf
author: aussiedwarf
email: aussiedwarf@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog of a software developer
baseurl: ""
twitter_username: aussiedwarf
github_username:  aussiedwarf

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
